# Generated by Django 3.0.6 on 2020-05-11 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Starting day and time')),
                ('end_time', models.DateTimeField(verbose_name='Ending day and time')),
                ('display_name', models.CharField(default='My SubRequest', max_length=50, verbose_name='The name for the Subrequest')),
                ('approved', models.BooleanField(default=False, verbose_name='Whether or not the subrequest has been approved')),
                ('covered_by', models.BooleanField(default=False, verbose_name='Who has covered the subrequest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
