# Generated by Django 3.0.5 on 2020-05-12 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0003_auto_20200512_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
