# Generated by Django 3.0.5 on 2020-05-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20200512_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subrequests',
            old_name='display_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='subrequests',
            name='anonymous',
            field=models.BooleanField(default=True, verbose_name='Whether or not you want your request to be anonymous'),
        ),
        migrations.AlterField(
            model_name='subrequests',
            name='covered_by',
            field=models.CharField(max_length=20, null=True, verbose_name='Who has covered the subrequest'),
        ),
    ]
