# Generated by Django 3.0.5 on 2020-05-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20200512_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='date',
            field=models.DateField(default='2020-05-12', verbose_name='day of shift'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shifts',
            name='end_time',
            field=models.TimeField(verbose_name='Ending day and time'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name of shift'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='start_time',
            field=models.TimeField(verbose_name='Starting day and time'),
        ),
    ]
