# Generated by Django 3.0.5 on 2020-05-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_auto_20200513_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrequests',
            name='date',
            field=models.DateField(default='2020-05-12', verbose_name='day of subrequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shifts',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='subrequests',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='subrequests',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
