# Generated by Django 3.0.5 on 2020-05-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_auto_20200513_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftgroup_name', models.CharField(max_length=30, verbose_name='Shift group name')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftGrouper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftgrouper', to='cal.ShiftGroups')),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftgrouper', to='cal.Shifts')),
            ],
        ),
    ]
