# Generated by Django 3.0.5 on 2020-05-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_shiftgrouper_shiftgroups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftgrouper',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='shiftgrouper',
            old_name='shift_id',
            new_name='shift',
        ),
    ]
