# Generated by Django 3.0.5 on 2020-05-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_auto_20200513_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftgroups',
            old_name='shiftgroup_name',
            new_name='name',
        ),
    ]
