# Generated by Django 3.0.5 on 2020-05-15 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0011_auto_20200513_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrequests',
            name='covered_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subrequest_covered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subrequests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrequest_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
