# Generated by Django 3.0.6 on 2020-05-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='coach', max_length=30),
        ),
    ]
