# Generated by Django 3.0.6 on 2020-05-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('C', 'Coach'), ('S', 'Swimmer')], default='S', max_length=30),
        ),
    ]
