# Generated by Django 3.0.5 on 2020-05-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200505_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
