# Generated by Django 3.0.6 on 2020-05-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200518_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetTag',
        ),
    ]
